version: 2.1
# ---
jobs:
  fail:
    docker: 
      - image: alpine
    steps:
      - run: echo "Not failing!"
      - run: 
          command: echo "Nevermind I'm fine!" 
          when: on_fail            
# ---
workflows:
  handle_failure:
    jobs:
      - fail
