version: 2.1
# ---
commands:
    print_pipeline_id:
      steps:
      - run: echo $CIRCLE_WORKFLOW_ID
    print_pipeline_id_alt:
      parameters:
          id:
            type: string
      steps:
      - run: echo << parameters.id >>
# ---
jobs:
  say_hi:
    docker: 
      - image: alpine
    steps:
      - print_pipeline_id
  say_hey:
    docker: 
      - image: alpine
    steps:
      - print_pipeline_id_alt:
          id: << pipeline.id >>
# ---
workflows:
  hey:
    jobs:
      - say_hi
      - say_hey