version: 2.1
# ---
jobs:
  fail:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
  react:
    docker: 
      - image: circleci/node:13.8.0
    when: on_fail
    steps:
      - run: echo "I'm fine!"
# ---
workflows:
  handle_failure:
    jobs:
      - fail
      - react