version: 2.1
# ---
commands:
    print_pipeline_id:
      steps:
      - run: echo $CIRCLE_WORKFLOW_ID
# ---
jobs:
  say_hi:
    docker: 
      - image: alpine
    steps:
      - run: 
          name: print something
          command: print_pipeline_id
# ---
workflows:
  hey:
    jobs:
      - say_hi