version: 2.1
# ---
jobs:
  fail:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: return 0 # 0 | 1
  react:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - when: 
          condition: on_fail
          steps:
            - run: echo "I'm fine!"
# ---
workflows:
  handle_failure:
    jobs:
      - fail
      - react